import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import { GlobalStyle } from '../styles/global'

export default function Home() {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </>
  )
}
