import Head from 'next/head'
import Forecast from '../components/Forecast'
import Sidebar from '../components/Sidebar'
import SearchProvider from '../contexts/Search'

import * as S from '../styles'

import { GlobalStyle } from '../styles/global'

export default function Home() {
  return (
    <SearchProvider>
      <S.Container>
        <GlobalStyle />
        <Head>
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Sidebar />
        <Forecast />
      </S.Container>
    </SearchProvider>
  )
}
